site:
  title: TW Forge
  url: https://docs.twforge.net
  start_page: en::index.adoc

content:
  sources:
    - url: .
      branches: HEAD
      start_paths:
        - docs-en
        - docs-de

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui

output:
  dir: ./build/site
